server:
  port: 1000
  tomcat:
    uri-encoding: utf-8
    #    请求大小不限制
    max-swallow-size: -1

spring:
  data:
    redis:
      host: localhost
      port: 5379
      database: 0
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        ip: 127.0.0.1  # 强制指定注册IP
    gateway:
      discovery:
        locator:
          enabled: true # 动态路由, 从注册中心根据微服务的名称获得目标节点地址
      routes:
        - id: authRoute  # 每一项路由规则都有一个唯一的id
          uri: lb://auth-service
          predicates:
            - Path=/auth/**,/passport/**
        - id: fileRoute  # 每一项路由规则都有一个唯一的id
          uri: lb://file-service
          predicates:
            - Path=/file/**
        - id: mainRoute  # 每一项路由规则都有一个唯一的id
          uri: lb://main-service
          predicates:
            - Path=/main/**,/userinfo/**, /friendRequest/**, /friendShip/**, /friendCircle/**, /friendCircleLiked/**, /friendCircleComment/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true


logging:
  level:
    root: info

knife4j:
  gateway:
    enabled: true
    strategy: manual
    discover:
      enabled: true
      version: openapi3
      excluded-services:
        - gateway
    routes:
      - name: auth-service
        service-name: auth-service
        context-path: /
        url: /auth-service/v3/api-docs?group=auth-service
        order: 1
      - name: main-service
        service-name: main-service
        context-path: /
        url: /main-service/v3/api-docs?group=main-service
        order: 2
      - name: file-service
        service-name: file-service
        context-path: /
        url: /file-service/v3/api-docs?group=file-service
        order: 2
