server:
  port: 8077
  tomcat:
    uri-encoding: utf-8
    #    请求大小不限制
    max-swallow-size: -1

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: cloudchat
    password: cloudchat
    virtual-host: cloudchat
  jackson:
    time-zone: Asia/Shanghai
  data:
    redis:
      host: localhost
      port: 5379
      database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:4406/cloudchat?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  application:
    name: main-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        ip: 127.0.0.1  # 强制指定注册IP

mybatis-plus:
  mapper-scan: com.cherry.mapper
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'main-service'
      paths-to-match: '/**'
      packages-to-scan: com.cherry.controller
knife4j:
  enable: false
  setting:
    language: zh_cn
