
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: cloudchat
    password: cloudchat
    virtual-host: cloudchat
  data:
    redis:
      host: localhost
      port: 5379
      database: 0

